version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app/client:delegated
      - client_node_modules:/app/client/node_modules
      - ./server:/app/server:delegated
      - server_node_modules:/app/server/node_modules
    entrypoint: ["/usr/local/bin/dev-entrypoint.sh"]
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite dev server port
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:kevjeff1@db:5432/beauty_bar
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kevjeff1
      - POSTGRES_DB=beauty_bar
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  client_node_modules:
  server_node_modules:
  postgres_data:
  redis_data: