version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - dev-network
    ports:
      - "3000:3000"  # Backend API
      - "5173:5173"  # Vite dev server
    environment:
      - NODE_ENV=development
      - PORT=3000    # Explicitly set port
      - VITE_API_URL=http://65.21.158.167:3000
      - DATABASE_URL=postgresql://postgres:kevjeff1@db:5432/beauty_bar_dev
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./client:/app/client:delegated
      - client_node_modules:/app/client/node_modules
      - ./server:/app/server:delegated
      - server_node_modules:/app/server/node_modules
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          memory: 2G
    entrypoint: ["/usr/local/bin/dev-entrypoint.sh"]
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    networks:
      - dev-network
    environment:
      - POSTGRES_DB=beauty_bar_dev  # Different DB name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kevjeff1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - dev-network

networks:
  dev-network:
    name: beauty-bar-dev-network

volumes:
  client_node_modules:
  server_node_modules:
  postgres_data:
  redis_data: