version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_URL=https://bookpal.ca
      - DATABASE_URL=postgresql://postgres:kevjeff1@db:5432/beauty_bar_prod
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 4G
    depends_on:
      - db
      - redis
    networks:
      - prod-network
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - prod-network
    restart: always

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kevjeff1
      - POSTGRES_DB=beauty_bar_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prod-network
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - prod-network
    restart: always

networks:
  prod-network:
    name: beauty-bar-prod-network

volumes:
  postgres_data:
  redis_data:
